# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7dc36b8b869ac492dd0ece4201d013c3d008ac8e6d8707f095d74819240402c75965b0780a19e9aa8b66e7b93a69af1459bf1699349c8c7166e87e9af58d326

test:
  secret_key_base: fb2384f78b7e0cc1e4a192b0952999448e94bdc45af060c5d125faef7697d06ee49e49af732b77df14273b3709caf7631344b887ec0fd0c2726e803de8bf288b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
